server:  
  servlet:
    context-path: /propostas
  port: ${PORT:8082}
  compression:
    enabled: true
    min-response-size: 1024
  
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/uaa/user  

eureka:  
  instance:
    hostname: localhost
    port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/   

spring:
  application:
    name: propostas-service
  datasource:
    url: jdbc:sqlserver://192.168.20.222:1433;databaseName=Conciliador
    username: homologacao
    password: ch@rtconcili@dor
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform:  org.hibernate.dialect.SQLServer2012Dialect
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
    serialization:
      indent-output: true
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true
    default-property-inclusion: non-empty
logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    br.com.conciliasolucoes: DEBUG
  file: propostas-service.log
      
      
